### PR TITLE
#162163134 create and view articles:

### PR DESCRIPTION
**Pull request by ekumamait**
**What does this PR do? Allow Authors to create articles**

- Allow Authors to create an article
- Allow Authors to view all articles
- Allow Authors to view a single article

 **Description of Task to be completed?**
Our application has no UI for creating and viewing articles. This task allows us to create a UI to create an article, view a single article and view all articles already created.

**How should this be manually tested?**

- Install dependencies: `yarn`
- Run the application server: `yarn start`
- To create an article go to `article/post` in the browser
- To see all articles go to `/articles` in the browser
- To see a single article click on that article to display it
- To edit an article click on the edit icon

**What are the relevant pivotal tracker stories?**
[ #162163134](https://www.pivotaltracker.com/story/show/162163134)

**Screenshots**
create an article:
screen shot 2019-01-17 at 9 29 56 am
view article feed:
screen shot 2019-01-17 at 9 29 06 am
view a single article:
screen shot 2019-01-17 at 9 59 29 am

### CODE REVIEW

**Review by ongebo — COMMENTED** [review]
Nice work @ekumamait , let's wait for the login functionality to be merged and pick the user's token from the State, not hard coded.

**Comment by RrNn** [comment]
There is a console error on the end point `/articles`.
screen shot 2019-01-24 at 19 53 44

**Comment by ekumamait** [comment]
> There is a console error on the end point `/articles`.
> screen shot 2019-01-24 at 19 53 44

**Comment by ekumamait** [comment]
> > There is a console error on the end point `/articles`.
> > screen shot 2019-01-24 at 19 53 44

Thanks for the feedback @RrNn I have fixed that, let me know what you think.

**Comment by ekumamait** [comment]
Thanks for the feedback @RrNn I have fixed that, let me know what you think.

**Pull request closed without merging**
