### PR TITLE
#162163125 Update TravisCI to run tests

### PR DESCRIPTION
**Pull request by barema4**
### What does this PR do?
Updates Travis to run tests
### Description of the task to be completed
- Integrate the Github repository with Travis ci
### How should this be manually tested?
- Add and push your commits to the Github repository
### What are the relevant pivotal tracker stories?
[#162163125](https://www.pivotaltracker.com/story/show/162163125)

### CODE REVIEW

**Review by sekayasin — APPROVED** [review]
Approved

**Review by alexkayabula — APPROVED** [review]
Looks good to me

**Review by lindseyme — APPROVED** [review]
Looks good to me

**Review by mulondo — APPROVED** [review]
good job

**Pull request merged**
