### PR TITLE
#162163123 Set up react/redux file structure

### PR DESCRIPTION
**Pull request by ekumamait**
**What does this PR do?**
 sets up react/redux 

**Description of Task to be completed?**
- installs redux to handle state management
- Installs react-redux to couple react with redux
- creates folders for the actions, reducers, constants and the redux store

**How should this be manually tested?**
The file structure can be seen in the screenshot below

**What are the relevant pivotal tracker stories?** 
[#162163123](https://www.pivotaltracker.com/story/show/162163123)

**Screenshots** 
screen shot 2019-01-09 at 3 23 06 pm

### CODE REVIEW

**Review by mulondo — APPROVED** [review]
good job

**Review by alexkayabula — APPROVED** [review]
Looks good

**Review by sekayasin — APPROVED** [review]
bravo

**Review by RrNn — CHANGES_REQUESTED** [review]
Good work here but your branch name doesn't follow the conventions here --> https://github.com/andela/engineering-playbook/tree/master/5.%20Developing/Conventions#commit-message. Remove the **#**
Also, we shall be using camelCase for variables and file names, so rename the file **src/constants/action-types** to **actionTypes** instead

**Comment by ekumamait** [comment]
Thank you @RrNn for that observation, let me rename the branch and raise a new Pull Request.

**Pull request closed without merging**
