### PR TITLE
#162163122 Setup an empty React project

### PR DESCRIPTION
**Pull request by ongebo**
## What does this PR do?
Sets up an empty React project
### Description of the task to be completed?
- Add .gitignore, README.md, and LICENSE.txt
- Initialize repository as an npm project (adds package.json)
- Add dependencies for Webpack, Babel and React to package.json
- Create .babelrc to configure Babel
- Add Webpack configuration to webpack.config.js
- Create basic application files (index.html, index.js, App.js)
- Configure hot reloading in App.js
- Setup ESLint using Airbnb rules
### How should this be manually tested?
- Install all dependencies using **yarn**
- Run the command `yarn start` to execute the development server
- Open `localhost:3000` in a browser to verify that the app is running
- To lint, use the command: `yarn run lint`
### Screenshot
app screenshot

### What are the relevant pivotal tracker stories?
[#162163122](https://www.pivotaltracker.com/story/show/162163122)

### CODE REVIEW

**Review by ekumamait — COMMENTED** [review]
Good work @ongebo but don't we need to include the eslint file!

**Review by lindseyme — APPROVED** [review]
Looks good to me.

**Comment by sekayasin** [comment]
Good work @ongebo, Yes, as @ekumamait says, we need also to setup linting, EsLint, in the description its Airbnb Linting.

**Comment by ongebo** [comment]
Thanks, @ekumamait and @sekayasin, I have setup ESlint to use Airbnb rules.

**Comment by ekumamait** [comment]
> Thanks, @ekumamait and @sekayasin, I have setup ESlint to use Airbnb rules.

LQTM

**Pull request merged**
