### PR TITLE
#163183160 Configure project for deployment to Heroku

### PR DESCRIPTION
**Pull request by ongebo**
### What does this PR do?
Adds configuration to the codebase to enable it to be deployed to Heroku.
#### Description of the task to be completed?
- Add **heroku-postbuild** script to package.json to create a production build
upon deployment to Heroku
- Add dependencies (express and path) for writing a production server
- Create an ExpressJS server in server.js to serve the production build
- Add a Procfile to run the production server on Heroku
#### How should this be manually tested?
- Add work to the develop branch (when a PR is merged)
- Click the link [https://zeus-fe.herokuapp.com](https://zeus-fe.herokuapp.com) to
verify that the changes have been deployed to Heroku
#### What are the relevant Pivotal Tracker stories?
[#163183160](https://www.pivotaltracker.com/story/show/163183160)

### CODE REVIEW

**Review by ekumamait — APPROVED** [review]
Nice work @ongebo

**Review by sekayasin — APPROVED** [review]
Looks good

**Review by alexkayabula — APPROVED** [review]
Nice work

**Review by barema4 — APPROVED** [review]
Nice work

**Pull request merged**
