### PR TITLE
 #162163124 Setup an environment for writing tests

### PR DESCRIPTION
**Pull request by sekayasin**
### What does this PR do?
Setup an environment for writing tests with jest and enzyme
#### Description of Task to be completed?
- Clone the repo, ```cd``` into the project ```rootdir``` and Install all dependencies by running the command below
```yarn``` 
- Inorder to test components, Write test files with ```.test.js``` suffix and save them in ```src/__tests__/``` folder 
#### How should this be manually tested?
- Inorder to run tests, run the command below. 
```yarn test --coverage```
- After running the command up, Jest will run tests related to files changed since the last commit.
#### What are the relevant pivotal tracker stories?
 [#162163124](https://www.pivotaltracker.com/story/show/162163124)
#### Screenshots (if appropriate)
screenshot 2019-01-09 at 15 47 22

### CODE REVIEW

**Review by alexkayabula — APPROVED** [review]
Nice work

**Review by barema4 — APPROVED** [review]
Looks nice

**Review by ongebo — APPROVED** [review]

**Review by ekumamait — APPROVED** [review]
Nice work including a test folder @sekayasin

**Comment by RrNn** [comment]
@sekayasin  Your **Description of Task to be completed?** looks terrible and the **How should this be manually tested?** is not any descriptive

**Review by RrNn — CHANGES_REQUESTED** [review]
@sekayasin Your Description of **Task to be completed?** looks terrible and the **How should this be manually tested?** is not any descriptive.
Also, let's move the __tests__ dir outside the **src** dir.

**Comment by sekayasin** [comment]
@RrNn Yes, about the __tests__ dir, been reading some [react docs](https://facebook.github.io/create-react-app/docs/running-tests), they recommend putting the test files or __tests__ folders at any depth under the src top-level folder. Any pointer on this, thanks

**Comment by RrNn** [comment]
@sekayasin , exclude **css files** from tests.

**Pull request closed without merging**
