### PR TITLE
#162163123 setup react-redux file structure

### PR DESCRIPTION
**Pull request by ekumamait**
**What does this PR do?**
 sets up react/redux 

**Description of Task to be completed?**
- Install redux to handle state management `yarn add redux`
- Install react-redux to couple react with redux `yarn add react-redux`
- create folders for the actions, reducers, constants and the redux store in the src folder

**How should this be manually tested?**
The file structure can be seen in the screenshot below

**What are the relevant pivotal tracker stories?** 
[#162163123](https://www.pivotaltracker.com/story/show/162163123)

**Screenshots** 
screen shot 2019-01-09 at 3 23 06 pm

### CODE REVIEW

**Comment by RrNn** [comment]
@ekumamait your description is not descriptive enough

**Comment by RrNn** [comment]
Let's remove the error in the console. Set up a test Reducer and pass it to your rootReducer, should be pretty easy & quick
screen shot 2019-01-10 at 12 40 24

**Comment by ekumamait** [comment]
> Let's remove the error in the console. Set up a test Reducer and pass it to your rootReducer, should be pretty easy & quick
> screen shot 2019-01-10 at 12 40 24
Alright, let me look into that

**Comment by ekumamait** [comment]
> > Let's remove the error in the console. Set up a test Reducer and pass it to your rootReducer, should be pretty easy & quick
> > screen shot 2019-01-10 at 12 40 24
> > Alright, let me look into that

@RrNn I have resolved that, let me know what you think?
screen shot 2019-01-10 at 2 35 11 pm

**Review by RrNn — APPROVED** [review]
LGTM

**Pull request merged**
